### PR TITLE
dependency lift + appropriate code changes and adjusted README since …

### PR DESCRIPTION
**Pull request by mppperez**
Fix for issue https://github.com/javascript-obfuscator/react-native-obfuscating-transformer/issues/43

### CODE REVIEW

**Comment by nicholaslee119** [comment]
@mppperez  Thanks for your work!
I check out your repo and built it locally, It seems to work well itself and return right `{ ast: ast }` But, after passing the `{ ast: ast }` to Metro, I can not get right `bundle.js` which should be obfuscated by this plugin.

**Comment by mppperez** [comment]
hi @nicholaslee119, could u provide a sample? I've just compared the `bundle.js` of my previous app version with old javascript obfuscator with the new one and it looks fine for me (only obfuscating app code not the third party libraries).

this discussion may be better in an own issue here referencing this PR.

best regards

**Comment by HyperNovax** [comment]
Perfect, this branch fixes the problems. The obfuscating is good but the application crashes on startup :
```
05-05 13:59:47.348 28558 28591 E AndroidRuntime: com.facebook.react.common.d: ReferenceError: Can't find variable: styles, stack:
05-05 13:59:47.348 28558 28591 E AndroidRuntime: <unknown>@1551:924
05-05 13:59:47.348 28558 28591 E AndroidRuntime: v@2:1473
05-05 13:59:47.348 28558 28591 E AndroidRuntime: <unknown>@1549:1296
05-05 13:59:47.348 28558 28591 E AndroidRuntime: v@2:1473
05-05 13:59:47.348 28558 28591 E AndroidRuntime: <unknown>@1515:961
05-05 13:59:47.348 28558 28591 E AndroidRuntime: v@2:1473
05-05 13:59:47.348 28558 28591 E AndroidRuntime: <unknown>@471:923
05-05 13:59:47.348 28558 28591 E AndroidRuntime: v@2:1473
05-05 13:59:47.348 28558 28591 E AndroidRuntime: <unknown>@405:228
05-05 13:59:47.348 28558 28591 E AndroidRuntime: v@2:1473
05-05 13:59:47.348 28558 28591 E AndroidRuntime: <unknown>@6:57
05-05 13:59:47.348 28558 28591 E AndroidRuntime: v@2:1473
05-05 13:59:47.348 28558 28591 E AndroidRuntime: d@2:875
05-05 13:59:47.348 28558 28591 E AndroidRuntime: global code@1612:3
```

**Comment by TheMatrixMaster** [comment]
What is the progress on this PR? I am also encountering this issue when bundling my app. @mppperez @nicholaslee119

**Comment by mppperez** [comment]
Unfortunately I do not have permission to merge the PR or make a release. You would need to apply the changes manually for now if you want to continue to use this lib.

I guess this will be my last PR for this as well (had another one for fixes with RN > 0.59) since it seems like this project won't be ressurected anymore although there are still many ppl left using it. Any suggestion for a good alternative are welcome ... probably ending up using javascript-obfuscator directly as already mentioned in  https://github.com/javascript-obfuscator/react-native-obfuscating-transformer/pull/15

**Comment by sanex3339** [comment]
I can merge it but i can't release it

**Comment by geraintwhite** [comment]
> I can merge it but i can't release it

Who can release it? @ds300 can you?

**Pull request merged**
